#ifndef NV2A_TRACE_REGISTER_DEFS_H
#define NV2A_TRACE_REGISTER_DEFS_H

#include "xemu/hw/xbox/nv2a/nv2a_regs.h"

// For general information on PFIFO, see
// https://envytools.readthedocs.io/en/latest/hw/fifo/intro.html

// mmio blocks
#define NV2A_MMIO_BASE 0xFD000000
#define BLOCK_PMC 0x000000
#define BLOCK_PBUS 0x001000
#define BLOCK_PFIFO 0x002000
#define BLOCK_PRMA 0x007000
#define BLOCK_PVIDEO 0x008000
#define BLOCK_PTIMER 0x009000
#define BLOCK_PCOUNTER 0x00A000
#define BLOCK_PVPE 0x00B000
#define BLOCK_PTV 0x00D000
#define BLOCK_PRMFB 0x0A0000
#define BLOCK_PRMVIO 0x0C0000
#define BLOCK_PFB 0x100000
#define BLOCK_PSTRAPS 0x101000
#define BLOCK_PGRAPH 0x400000
#define BLOCK_PCRTC 0x600000
#define BLOCK_PRMCIO 0x601000
#define BLOCK_PRAMDAC 0x680000
#define BLOCK_PRMDIO 0x681000
#define BLOCK_PRAMIN 0x700000
#define BLOCK_USER 0x800000

#define _PFIFO_ADDR(addr) (NV2A_MMIO_BASE + BLOCK_PFIFO + (addr))
#define _PGRAPH_ADDR(addr) (NV2A_MMIO_BASE + BLOCK_PGRAPH + (addr))

#define DMA_STATE _PFIFO_ADDR(NV_PFIFO_CACHE1_DMA_STATE)
#define DMA_PUSH_ADDR _PFIFO_ADDR(NV_PFIFO_CACHE1_DMA_PUT)
#define DMA_PULL_ADDR _PFIFO_ADDR(NV_PFIFO_CACHE1_DMA_GET)
#define DMA_SUBROUTINE _PFIFO_ADDR(NV_PFIFO_CACHE1_DMA_SUBROUTINE)
#define CACHE_PUSH_MASTER_STATE _PFIFO_ADDR(NV_PFIFO_CACHE1_PUSH0)
#define CACHE_PUSH_STATE _PFIFO_ADDR(NV_PFIFO_CACHE1_DMA_PUSH)
#define CACHE_PULL_STATE _PFIFO_ADDR(NV_PFIFO_CACHE1_PULL0)
#define CACHE_PUSH_ADDR _PFIFO_ADDR(NV_PFIFO_CACHE1_PUT)
#define CACHE_PULL_ADDR _PFIFO_ADDR(NV_PFIFO_CACHE1_GET)
#define CACHE1_METHOD _PFIFO_ADDR(NV_PFIFO_CACHE1_METHOD)
#define CACHE1_DATA _PFIFO_ADDR(NV_PFIFO_CACHE1_DATA)
#define RAM_HASHTABLE _PFIFO_ADDR(NV_PFIFO_RAMHT)

#define CTX_SWITCH1 _PGRAPH_ADDR(NV_PGRAPH_CTX_SWITCH1)
#define PGRAPH_STATE _PGRAPH_ADDR(NV_PGRAPH_FIFO)
#define NV_PGRAPH_STATUS 0x00000700
#define PGRAPH_STATUS _PGRAPH_ADDR(NV_PGRAPH_STATUS)
#define PGRAPH_TEXOFFSET0 _PGRAPH_ADDR(NV_PGRAPH_TEXOFFSET0)
#define PGRAPH_TEXCTL0_0 _PGRAPH_ADDR(NV_PGRAPH_TEXCTL0_0)
#define PGRAPH_TEXCTL1_0 _PGRAPH_ADDR(NV_PGRAPH_TEXCTL1_0)
#define PGRAPH_TEXFMT0 _PGRAPH_ADDR(NV_PGRAPH_TEXFMT0)
#define PGRAPH_TEXIMAGERECT0 _PGRAPH_ADDR(NV_PGRAPH_TEXIMAGERECT0)

#define PGRAPH_CTX_CACHE1(subchannel) \
  _PGRAPH_ADDR(NV_PGRAPH_CTX_CACHE1 + (subchannel << 2))

#endif  // NV2A_TRACE_REGISTER_DEFS_H
